dist: bionic
addons:
  apt:
    packages:
      - lftp
      - bgpdump
language: rust
cache: cargo
env:
  global:
  - BGPTOOLS_VERSION=0.0.3
before_script:
  - go get github.com/zhanhb/cidr-merger
  - export
  - cidr-merger -v
  - bgptools --version | grep -F $BGPTOOLS_VERSION || cargo install --vers $BGPTOOLS_VERSION bgptools
  - export PATH=$PATH:$HOME/.cargo/bin:$HOME/go/bin
script:
  - ./generate.sh
  - ./stat.sh
deploy:
  provider: script
  script: ./upload.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE == cron
