dist: bionic
addons:
  apt:
    packages:
      - lftp
      - bgpdump
language: rust
cache:
  cargo: true
  directories:
    - /home/travis/gopath/bin
env:
  global:
  - BGPTOOLS_VERSION=0.0.3
before_script:
  - cidr-merger -v || go get github.com/zhanhb/cidr-merger
  - bgptools --version | grep -F $BGPTOOLS_VERSION || cargo install --vers $BGPTOOLS_VERSION bgptools
script:
  - ./generate.sh
  - ./stat.sh
deploy:
  provider: script
  script: ./upload.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE == cron
