sudo: required
dist: bionic
addons:
  apt:
    packages:
      - lftp
      - bgpdump
language: rust
go:
  - 1.12.x
cache: cargo
env:
  global:
  - BGPTOOLS_VERSION=0.0.3
before_script:
  - go version
  - bgptools --version | grep -F $BGPTOOLS_VERSION || cargo install --vers $BGPTOOLS_VERSION bgptools
  - export PATH=$PATH:/home/travis/.cargo/bin
  - docker pull yangzhaofengsteven/cidr-merge
script:
  - ./generate.sh
  - ./stat.sh
deploy:
  provider: script
  script: ./upload.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE == cron
